# Generated by Django 4.2.7 on 2023-11-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0005_alter_caracteristica_nombre_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('estado_producto', models.IntegerField(choices=[(0, 'En carrito'), (1, 'Pendiente'), (2, 'Reservado'), (3, 'Finalizado')], default=0)),
                ('estado_envio', models.IntegerField(choices=[(0, 'En almacen'), (1, 'En reparto'), (2, 'Entregado')], default=0)),
                ('tipo_pago', models.IntegerField(choices=[(0, 'Contrareembolso'), (1, 'Pasarela')], default=1)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='producto.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
    ]
