# Generated by Django 4.2.7 on 2023-12-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_reclamacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='usuario',
        ),
    ]
