# Generated by Django 4.2.7 on 2023-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_itemventa_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sesion_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
