# Generated by Django 4.2.7 on 2023-12-04 18:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AT', 'Autonomía'), ('VM', 'Velocidad máxima'), ('TC', 'Tiempo de carga'), ('P', 'Peso')], max_length=50)),
                ('valor', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'caracteristica',
                'verbose_name_plural': 'caracteristicas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('url_imagen', models.URLField()),
                ('precio_base', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=1)),
                ('empresa', models.CharField(choices=[('Harley Davidson', 'Harley Davidson'), ('Ducati', 'Ducati'), ('Aprilia', 'Aprilia'), ('BMW', 'BMW'), ('Yamaha', 'Yamaha'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki'), ('Kawasaki', 'Kawasaki'), ('KTM', 'KTM'), ('Triumph', 'Triumph'), ('Aprilia', 'Aprilia'), ('Benelli', 'Benelli'), ('Kawasaki', 'Kawasaki'), ('Suzuki', 'Suzuki'), ('Montesa', 'Montesa'), ('Moto Guzzi', 'Moto Guzzi')], max_length=100)),
                ('caracteristicas', models.ManyToManyField(to='producto.caracteristica')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_item_carrito', to='tienda.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=500)),
                ('fecha_comentario', models.DateField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
    ]
