# Generated by Django 4.2.7 on 2023-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.CharField(choices=[('', 'Todos los modelos'), ('Harley Davidson', 'Harley Davidson'), ('Ducati', 'Ducati'), ('Aprilia', 'Aprilia'), ('BMW', 'BMW'), ('Yamaha', 'Yamaha'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki'), ('Kawasaki', 'Kawasaki'), ('KTM', 'KTM'), ('Triumph', 'Triumph'), ('Aprilia', 'Aprilia'), ('Benelli', 'Benelli'), ('Kawasaki', 'Kawasaki'), ('Suzuki', 'Suzuki'), ('Montesa', 'Montesa'), ('Moto Guzzi', 'Moto Guzzi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
