# Generated by Django 4.2.7 on 2023-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_empresa_nombre_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'caracteristica',
                'verbose_name_plural': 'caracteristicas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(to='producto.caracteristica'),
        ),
    ]
