# Generated by Django 4.2.7 on 2023-12-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_empresa_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='venta',
        ),
    ]
