# Generated by Django 4.2.7 on 2023-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_caracteristica_producto_precio_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(choices=[('AT', 'Autonomía'), ('VM', 'Velocidad máxima'), ('TC', 'Tiempo de carga'), ('SF', 'Sistema de frenado'), ('B', 'Batería'), ('P', 'Peso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
