# Generated by Django 4.2.7 on 2023-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_caracteristica_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(choices=[('AT', 'Autonomía'), ('VM', 'Velocidad máxima'), ('TC', 'Tiempo de carga'), ('P', 'Peso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='valor',
            field=models.IntegerField(max_length=20),
        ),
    ]
