# Generated by Django 4.2.7 on 2023-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_caracteristica_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
