# Generated by Django 4.2.7 on 2023-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.CharField(choices=[('Harley Davidson', 'Harley Davidson'), ('Ducati', 'Ducati'), ('Aprilia', 'Aprilia'), ('BMW', 'BMW'), ('Yamaha', 'Yamaha'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki'), ('Kawasaki', 'Kawasaki'), ('KTM', 'KTM'), ('Triumph', 'Triumph'), ('Aprilia', 'Aprilia'), ('Benelli', 'Benelli'), ('Kawasaki', 'Kawasaki'), ('Suzuki', 'Suzuki'), ('Montesa', 'Montesa'), ('Moto Guzzi', 'Moto Guzzi')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
