# Generated by Django 4.2.7 on 2023-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_comentario'),
        ('producto', '0010_alter_producto_precio_base'),
    ]

    operations = [
    ]
