# Generated by Django 4.2.7 on 2023-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_merge_0008_comentario_0010_alter_producto_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateField(auto_now=True),
        ),
    ]
