# Generated by Django 4.2.7 on 2023-12-04 18:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='El IBAN debe tener 16 dígitos numéricos', regex='^\\d{16}$')])),
                ('fecha_caducidad', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='El formato de la fecha de caducidad no es el correcto', regex='^\\d{2}/\\d{2}$')])),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El CVV debe tener 3 dígitos numéricos', regex='^\\d{3}$')])),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, validators=[usuario.models.validar_fecha])),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato invalido.', regex='^\\+?1?\\d{9,15}$')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('apartamento', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('ESP', 'ESP')], max_length=100)),
                ('ciudad', models.CharField(choices=[('Huelva', 'Huelva'), ('Sevilla', 'Sevilla'), ('Cordoba', 'Cordoba'), ('Jaen', 'Jaen'), ('Cadiz', 'Cadiz'), ('Malaga', 'Malaga'), ('Granada', 'Granada'), ('Almeria', 'Almeria'), ('Badajoz', 'Badajoz'), ('Ciudad Real', 'Ciudad Real'), ('Albacete', 'Albacete'), ('Murcia', 'Murcia'), ('Alicante', 'Alicante'), ('Caceres', 'Caceres'), ('Toledo', 'Toledo'), ('Cuenca', 'Cuenca'), ('Valencia', 'Valencia'), ('Salamanca', 'Salamanca'), ('Avila', 'Avila'), ('Madrid', 'Madrid'), ('Guadalajara', 'Guadalajara'), ('Teruel', 'Teruel'), ('Castellon', 'Castellon'), ('Zamora', 'Zamora'), ('Valladolid', 'Valladolid'), ('Segovia', 'Segovia'), ('Soria', 'Soria'), ('Zaragoza', 'Zaragoza'), ('Tarragona', 'Tarragona'), ('Pontevedra', 'Pontevedra'), ('Orense', 'Orense'), ('Leon', 'Leon'), ('Palencia', 'Palencia'), ('Burgos', 'Burgos'), ('La Rioja', 'La Rioja'), ('Navarra', 'Navarra'), ('Huesca', 'Huesca'), ('Lerida', 'Lerida'), ('Barcelona', 'Barcelona'), ('Gerona', 'Gerona'), ('Navarra', 'Navarra'), ('Vizacaya', 'Vizcaya'), ('Guipuzcoa', 'Guipuzcoa'), ('Alava', 'Alava'), ('Cantabria', 'Cantabria'), ('Asturias', 'Asturias'), ('Lugo', 'Lugo'), ('La Coruña', 'La Coruña')], max_length=100)),
                ('codigo_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener 5 dígitos exactamente', regex='^\\d{5}$')])),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': 'direcciones',
            },
        ),
    ]
