# Generated by Django 4.2.7 on 2023-11-28 10:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(validators=[usuario.models.validar_fecha])),
                ('telefono', models.CharField(help_text='El numero de telefono debe ser ingresado en formato internacional', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato invalido.', regex='^\\+?1?\\d{9,15}$')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('apartamento', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('ESP', 'ESP')], max_length=100)),
                ('ciudad', models.CharField(choices=[('Huelva', 'Huelva'), ('Sevilla', 'Sevilla'), ('Cordoba', 'Cordoba'), ('Jaen', 'Jaen'), ('Cadiz', 'Cadiz'), ('Malaga', 'Malaga'), ('Granada', 'Granada'), ('Almeria', 'Almeria'), ('Badajoz', 'Badajoz'), ('Ciudad Real', 'Ciudad Real'), ('Albacete', 'Albacete'), ('Murcia', 'Murcia'), ('Alicante', 'Alicante'), ('Caceres', 'Caceres'), ('Toledo', 'Toledo'), ('Cuenca', 'Cuenca'), ('Valencia', 'Valencia'), ('Salamanca', 'Salamanca'), ('Avila', 'Avila'), ('Madrid', 'Madrid'), ('Guadalajara', 'Guadalajara'), ('Teruel', 'Teruel'), ('Castellon', 'Castellon'), ('Zamora', 'Zamora'), ('Valladolid', 'Valladolid'), ('Segovia', 'Segovia'), ('Soria', 'Soria'), ('Zaragoza', 'Zaragoza'), ('Tarragona', 'Tarragona'), ('Pontevedra', 'Pontevedra'), ('Orense', 'Orense'), ('Leon', 'Leon'), ('Palencia', 'Palencia'), ('Burgos', 'Burgos'), ('La Rioja', 'La Rioja'), ('Navarra', 'Navarra'), ('Huesca', 'Huesca'), ('Lerida', 'Lerida'), ('Barcelona', 'Barcelona'), ('Gerona', 'Gerona'), ('Navarra', 'Navarra'), ('Vizacaya', 'Vizcaya'), ('Guipuzcoa', 'Guipuzcoa'), ('Alava', 'Alava'), ('Cantabria', 'Cantabria'), ('Asturias', 'Asturias'), ('Lugo', 'Lugo'), ('La Coruña', 'La Coruña')], max_length=100)),
                ('codigo_postal', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(limit_value=5, message='El codigo postal debe contener 5 digitos exactamente'), django.core.validators.MinValueValidator(limit_value=5, message='El codigo postal debe contener 5 digitos exactamente')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
