# Generated by Django 4.2.7 on 2023-11-28 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_direccion_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'direccion', 'verbose_name_plural': 'direcciones'},
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='El codigo postal debe contener 5 digitos exactamente'), django.core.validators.MinValueValidator(limit_value=5, message='El codigo postal debe contener 5 digitos exactamente')]),
        ),
    ]
