# Generated by Django 4.2.7 on 2023-11-28 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_direccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=6, message='El codigo postal debe contener 5 digitos exactamente'), django.core.validators.MinValueValidator(limit_value=5, message='El codigo postal debe contener 5 digitos exactamente')]),
        ),
    ]
