# Generated by Django 4.2.7 on 2023-11-28 18:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0006_alter_direccion_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener 5 dígitos exactamente', regex='^\\d{5}$')]),
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=30)),
                ('fecha_caducidad', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
            },
        ),
    ]
