# Generated by Django 4.2.7 on 2023-11-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_direccion_codigo_postal_tarjetacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_caducidad',
            field=models.CharField(max_length=5),
        ),
    ]
