# Generated by Django 4.2.7 on 2023-11-29 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_tarjetacredito_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_caducidad',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El formato de la fecha de caducidad no es el correcto', regex='^\\d{2}/\\d{2}$')]),
        ),
    ]
