# Generated by Django 4.2.7 on 2023-11-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_perfil_fecha_nacimiento_alter_perfil_telefono'),
        ('usuario', '0009_alter_tarjetacredito_fecha_caducidad'),
    ]

    operations = [
    ]
