# Generated by Django 4.2.7 on 2023-11-29 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_direccion_codigo_postal_alter_perfil_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El CVV debe tener 4 dígitos numéricos', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_caducidad',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='El formato de la fecha de caducidad no es el correcto', regex='^\\d{2}/\\d{4}$')]),
        ),
    ]
