# Generated by Django 4.2.7 on 2023-12-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_perfil_telefono'),
        ('usuario', '0012_alter_tarjetacredito_cvv_and_more'),
    ]

    operations = [
    ]
