# Generated by Django 4.2.7 on 2023-12-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_tarjetacredito_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
