# Generated by Django 4.2.7 on 2023-12-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_merge_20231201_1240'),
        ('usuario', '0016_alter_perfil_options'),
    ]

    operations = [
    ]
