# Generated by Django 4.2.7 on 2023-12-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_merge_20231130_2256'),
        ('usuario', '0013_merge_20231201_1526'),
        ('usuario', '0017_merge_20231203_1157'),
    ]

    operations = [
    ]
