# Generated by Django 4.2.7 on 2023-12-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_merge_20231201_1526'),
        ('usuario', '0018_merge_20231203_1222'),
    ]

    operations = [
    ]
